// <auto-generated />
using System;
using CookIt.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookIt.Infrastructure.Migrations
{
    [DbContext(typeof(CookItContext))]
    [Migration("20251127080909_addNutritionInfo")]
    partial class addNutritionInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookIt.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b8f6982f-8c8a-40cf-8350-6fccb723cf34",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59a80b94-5765-4bf9-ac42-2cca148f6eb2",
                            Email = "admin@cookit.com",
                            EmailConfirmed = true,
                            FullName = "admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@COOKIT.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECJp7LhsC6Be7WPS0mPtlJt9Px5Eje2mpCAH+DXXNCr/PfJE2aH3blhK6fpym4YQMA==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4G4YRSV6FEXCB6A7DC2YXLSDI5Q3XXFJ",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.DishType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DishTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Напиток"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Основное блюдо"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Гарнир"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Закуска"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Салат"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Десерт"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Суп"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Духовка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Плита"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Миксер"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Блендер"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Мультиварка"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Микроволновка"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кастрюля"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Сковорода"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Венчик"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Мерный стакан"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Форма для выпечки"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsByPiece")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 364.0,
                            Carbohydrates = 76.099999999999994,
                            Fats = 1.1000000000000001,
                            IsByPiece = false,
                            Name = "Мука",
                            Proteins = 10.300000000000001
                        },
                        new
                        {
                            Id = 2,
                            Calories = 387.0,
                            Carbohydrates = 99.799999999999997,
                            Fats = 0.0,
                            IsByPiece = false,
                            Name = "Сахар",
                            Proteins = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Calories = 0.0,
                            Carbohydrates = 0.0,
                            Fats = 0.0,
                            IsByPiece = false,
                            Name = "Соль",
                            Proteins = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Calories = 157.0,
                            Carbohydrates = 0.69999999999999996,
                            Fats = 11.5,
                            IsByPiece = true,
                            Name = "Яйцо",
                            Proteins = 12.699999999999999
                        },
                        new
                        {
                            Id = 5,
                            Calories = 60.0,
                            Carbohydrates = 4.7999999999999998,
                            Fats = 3.6000000000000001,
                            IsByPiece = false,
                            Name = "Молоко",
                            Proteins = 3.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            Calories = 717.0,
                            Carbohydrates = 0.80000000000000004,
                            Fats = 81.0,
                            IsByPiece = false,
                            Name = "Масло сливочное",
                            Proteins = 0.5
                        },
                        new
                        {
                            Id = 7,
                            Calories = 884.0,
                            Carbohydrates = 0.0,
                            Fats = 100.0,
                            IsByPiece = false,
                            Name = "Подсолнечное масло",
                            Proteins = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Calories = 77.0,
                            Carbohydrates = 16.300000000000001,
                            Fats = 0.40000000000000002,
                            IsByPiece = false,
                            Name = "Картофель",
                            Proteins = 2.0
                        },
                        new
                        {
                            Id = 9,
                            Calories = 40.0,
                            Carbohydrates = 9.3000000000000007,
                            Fats = 0.10000000000000001,
                            IsByPiece = false,
                            Name = "Лук",
                            Proteins = 1.1000000000000001
                        },
                        new
                        {
                            Id = 10,
                            Calories = 149.0,
                            Carbohydrates = 33.100000000000001,
                            Fats = 0.5,
                            IsByPiece = false,
                            Name = "Чеснок",
                            Proteins = 6.4000000000000004
                        },
                        new
                        {
                            Id = 11,
                            Calories = 41.0,
                            Carbohydrates = 9.5999999999999996,
                            Fats = 0.20000000000000001,
                            IsByPiece = false,
                            Name = "Морковь",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            Id = 12,
                            Calories = 190.0,
                            Carbohydrates = 0.0,
                            Fats = 12.0,
                            IsByPiece = false,
                            Name = "Курица",
                            Proteins = 20.0
                        },
                        new
                        {
                            Id = 13,
                            Calories = 250.0,
                            Carbohydrates = 0.0,
                            Fats = 15.0,
                            IsByPiece = false,
                            Name = "Говядина",
                            Proteins = 26.0
                        },
                        new
                        {
                            Id = 14,
                            Calories = 130.0,
                            Carbohydrates = 28.199999999999999,
                            Fats = 0.29999999999999999,
                            IsByPiece = false,
                            Name = "Рис",
                            Proteins = 2.7000000000000002
                        },
                        new
                        {
                            Id = 15,
                            Calories = 18.0,
                            Carbohydrates = 3.8999999999999999,
                            Fats = 0.20000000000000001,
                            IsByPiece = false,
                            Name = "Помидоры",
                            Proteins = 0.90000000000000002
                        },
                        new
                        {
                            Id = 16,
                            Calories = 15.0,
                            Carbohydrates = 3.6000000000000001,
                            Fats = 0.10000000000000001,
                            IsByPiece = false,
                            Name = "Огурцы",
                            Proteins = 0.69999999999999996
                        },
                        new
                        {
                            Id = 17,
                            Calories = 360.0,
                            Carbohydrates = 0.0,
                            Fats = 30.0,
                            IsByPiece = false,
                            Name = "Сыр",
                            Proteins = 23.0
                        },
                        new
                        {
                            Id = 18,
                            Calories = 206.0,
                            Carbohydrates = 3.3999999999999999,
                            Fats = 20.0,
                            IsByPiece = false,
                            Name = "Сметана",
                            Proteins = 2.5
                        },
                        new
                        {
                            Id = 19,
                            Calories = 624.0,
                            Carbohydrates = 0.59999999999999998,
                            Fats = 70.0,
                            IsByPiece = false,
                            Name = "Майонез",
                            Proteins = 0.29999999999999999
                        },
                        new
                        {
                            Id = 20,
                            Calories = 36.0,
                            Carbohydrates = 6.4000000000000004,
                            Fats = 0.40000000000000002,
                            IsByPiece = false,
                            Name = "Зелень",
                            Proteins = 2.6000000000000001
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTimeWithUser")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTimeWithoutUser")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DishTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpicinessLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishTypeId");

                    b.ToTable("Recipes", t =>
                        {
                            t.HasCheckConstraint("CK_Recipe_CookingTimeWithUser_Range", "\"CookingTimeWithUser\" >= 1");

                            t.HasCheckConstraint("CK_Recipe_CookingTimeWithoutUser_Range", "\"CookingTimeWithoutUser\" >= 1");

                            t.HasCheckConstraint("CK_Recipe_DifficultyLevel_Range", "\"DifficultyLevel\" >= 1 AND \"DifficultyLevel\" <= 5");

                            t.HasCheckConstraint("CK_Recipe_SpicinessLevel_Range", "\"SpicinessLevel\" >= 1 AND \"SpicinessLevel\" <= 5");
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeEquipment", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RecipeEquipments");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int?>("UnitId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeRating", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeRatings", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeRating_Value_Range", "\"Value\" >= 1 AND \"Value\" <= 5");
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("ConversionToGrams")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConversionToGrams = 1.0,
                            Name = "г"
                        },
                        new
                        {
                            Id = 2,
                            ConversionToGrams = 1000.0,
                            Name = "кг"
                        },
                        new
                        {
                            Id = 3,
                            ConversionToGrams = 1.0,
                            Name = "мл"
                        },
                        new
                        {
                            Id = 4,
                            ConversionToGrams = 1000.0,
                            Name = "л"
                        },
                        new
                        {
                            Id = 5,
                            Name = "шт"
                        },
                        new
                        {
                            Id = 6,
                            ConversionToGrams = 5.0,
                            Name = "ч.л."
                        },
                        new
                        {
                            Id = 7,
                            ConversionToGrams = 15.0,
                            Name = "ст.л."
                        },
                        new
                        {
                            Id = 8,
                            ConversionToGrams = 250.0,
                            Name = "стакан"
                        },
                        new
                        {
                            Id = 9,
                            Name = "щепотка"
                        },
                        new
                        {
                            Id = 10,
                            Name = "по вкусу"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.UserFavorite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b8633e2d-a33b-45e6-8329-1958b3252bbd",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b8f6982f-8c8a-40cf-8350-6fccb723cf34",
                            RoleId = "8e445865-a24d-4543-a6c6-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CookIt.Core.Entities.Recipe", b =>
                {
                    b.HasOne("CookIt.Core.Entities.DishType", "DishType")
                        .WithMany()
                        .HasForeignKey("DishTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishType");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeEquipment", b =>
                {
                    b.HasOne("CookIt.Core.Entities.Equipment", "Equipment")
                        .WithMany("RecipeEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeEquipments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("CookIt.Core.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeRating", b =>
                {
                    b.HasOne("CookIt.Core.Entities.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.ApplicationUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookIt.Core.Entities.UserFavorite", b =>
                {
                    b.HasOne("CookIt.Core.Entities.Recipe", "Recipe")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.ApplicationUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CookIt.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CookIt.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CookIt.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookIt.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Equipment", b =>
                {
                    b.Navigation("RecipeEquipments");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Recipe", b =>
                {
                    b.Navigation("FavoritedBy");

                    b.Navigation("Ratings");

                    b.Navigation("RecipeEquipments");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
