// <auto-generated />
using CookIt.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookIt.Infrastructure.Migrations
{
    [DbContext(typeof(CookItContext))]
    [Migration("20250420055253_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookIt.Core.Entities.DishType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DishTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Напиток"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Основное блюдо"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Гарнир"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Закуска"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Салат"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Десерт"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Суп"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Духовка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Плита"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Миксер"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Блендер"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Мультиварка"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Микроволновка"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кастрюля"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Сковорода"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Венчик"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Мерный стакан"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Форма для выпечки"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мука"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Сахар"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Соль"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Яйцо"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Молоко"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Масло сливочное"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Подсолнечное масло"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Картофель"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Лук"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Чеснок"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Морковь"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Курица"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Говядина"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Рис"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Помидоры"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Огурцы"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Сыр"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Сметана"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Майонез"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Зелень"
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTimeWithUser")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTimeWithoutUser")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DishTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpicinessLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishTypeId");

                    b.ToTable("Recipes", t =>
                        {
                            t.HasCheckConstraint("CK_Recipe_DifficultyLevel_Range", "\"DifficultyLevel\" >= 0 AND \"DifficultyLevel\" <= 5");

                            t.HasCheckConstraint("CK_Recipe_SpicinessLevel_Range", "\"SpicinessLevel\" >= 0 AND \"SpicinessLevel\" <= 5");
                        });
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeEquipment", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RecipeEquipments");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Recipe", b =>
                {
                    b.HasOne("CookIt.Core.Entities.DishType", "DishType")
                        .WithMany()
                        .HasForeignKey("DishTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishType");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeEquipment", b =>
                {
                    b.HasOne("CookIt.Core.Entities.Equipment", "Equipment")
                        .WithMany("RecipeEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeEquipments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookIt.Core.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("CookIt.Core.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookIt.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Equipment", b =>
                {
                    b.Navigation("RecipeEquipments");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CookIt.Core.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeEquipments");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
